# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/iosource/remote/src/const.bif (plugin mode).

export {
module PcapRemote;











} # end of export section
module GLOBAL;
