# This file was automatically generated by bifcl from messaging.bif (alternative mode).


##! Placeholder for Broker-based communication functionality, not enabled
##! by default
export {
} # end of export section
module GLOBAL;
