#!/bin/sh
# chkconfig: 345 35 65
# description: Aegis daemon
### BEGIN INIT INFO
# Provides:          aegis
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Start Aegis daemon
### END INIT INFO

PIDFILE="/usr/local/aegis/aegis.pid"

system=unknown
if [ -f /etc/redhat-release ]; then
    system=redhat
elif [ -f /etc/SuSE-release ]; then
    system=suse
elif [ -f /etc/arch-release ]; then
    system=arch
elif [ -f /etc/debian_version ]; then
    system=debian
elif [ -f /etc/gentoo-release ]; then
    system=gentoo
elif [ -f /etc/slackware-version ]; then
    system=slackware
elif [ -f /etc/lfs-release ]; then
    system=lfs
elif [[ $OSTYPE == darwin* ]]; then
    system=darwin
else
    system=other
fi

#set -e
set +x

NAME=aegis
DAEMON=/usr/local/aegis/bin/aegis
DESC="Aegis daemon"

test -x $DAEMON || (echo "missing aegis executable!" && exit 0)

DIR=/usr/local/aegis/
RETRY=15

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

if [ "$system" = "redhat" ]; then
. /etc/init.d/functions
    rundaemon() {
        daemon $DAEMON
        RETVAL=$?
        return $RETVAL
    }
fi

if [ "$system" = "suse" ]; then
    . /etc/rc.status
    rundaemon() {
        startproc $DAEMON >/dev/null 2>&1
    }
fi

if [ "$system" = "debian" ]; then
    rundaemon() {
	start-stop-daemon --oknodo --start --pidfile $PIDFILE --exec $DAEMON >/dev/null 2>&1
    }

    killproc() {
        start-stop-daemon --oknodo --stop --retry 2 --exec $@ --retry $RETRY
    }
fi

if [ "$system" = "gentoo" ]; then
    if [ -f /sbin/functions.sh ]; then
        . /sbin/functions.sh
    elif [ -f /etc/init.d/functions.sh ]; then
        . /etc/init.d/functions.sh
    fi

    rundaemon() {
        start-stop-daemon --start --exec $DAEMON >/dev/null 2>&1
    }

    killproc() {
        start-stop-daemon --stop --retry 2 --exec $@
    }

    if [ "`which $0`" = "/sbin/rc" ]; then
        shift
    fi
fi

if [ "$system" = "slackware" -o "$system" = "other" ]; then
    rundaemon() {
        $DAEMON >/dev/null 2>&1
    }

    killproc() {
        killall $1
        rm -f $PIDFILE
    }
fi

if [ "$system" = "lfs" ]; then
    . /etc/rc.d/init.d/functions
    rundaemon() {
        loadproc $DAEMON >/dev/null 2>&1
    }

    status() {
        statusproc $1
    }
fi

start() {
    echo "Starting $DESC" "$NAME"
    rundaemon

    case "$?" in
        0) echo " ...done" ;;
        *) echo " ...fail!"; exit 1 ;;
    esac
}

stop() {
    echo "Stopping $DESC" "$NAME"
    killproc $DAEMON
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
}

showstatus() {
   ls -l /proc/`cat $PIDFILE`/exe > /dev/null 2>&1
   if [ $? -eq 0 ]; then
       echo "$DESC is running"
       exit 0
   else
       echo "$DESC is NOT running"
       exit 1
   fi
}

restart() {
   stop && start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $DAEMON
	;;
  restart|force-reload)
	restart
	;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
