# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/analyzer/tn5250/src/events.bif (plugin mode).

export {
global telnet_command: event(c: connection , command: count , option: count , data: string );

global telnet_text: event(c: connection , text: string );


global tn5250_command: event(c: connection , command: count );

global tn5250_write: event(c: connection , command: count , text: string );

} # end of export section
module GLOBAL;
