# This file was automatically generated by bifcl from ..\..\input\updater\src\events.bif (plugin mode).

export {
global remote_command: event(command: string );

global remote_update_setting: event(name: string , value: string );


module Updater;

} # end of export section
module GLOBAL;
