# This file was automatically generated by bifcl from /apps/buildAgent/work/800d28ace6035b11/src/input/readers/binary/binary.bif (plugin mode).


export {
module InputBinary;



} # end of export section
module GLOBAL;
