# This file was automatically generated by bifcl from /apps/buildAgent/work/800d28ace6035b11/src/logging/writers/sqlite/sqlite.bif (plugin mode).




export {
module LogSQLite;






} # end of export section
module GLOBAL;
