# This file was automatically generated by bifcl from /apps/buildAgent/work/800d28ace6035b11/src/input/readers/raw/raw.bif (plugin mode).


export {
module InputRaw;



} # end of export section
module GLOBAL;
