# This file was automatically generated by bifcl from /build/sageaxcess-parsers/analyzer/gssapi/events.bif (plugin mode).

## Generated for GSSAPI negotiation results.
##
## c: The connection.
##
## state: The resulting state of the negotiation.
##
export {
global gssapi_neg_result: event(c: connection , state: count );

} # end of export section
module GLOBAL;
