# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/analyzer/gssapi/events.bif (plugin mode).

## Generated for GSSAPI negotiation results.
##
## c: The connection.
##
## state: The resulting state of the negotiation.
##
export {
global gssapi_neg_result: event(c: connection , state: count );

} # end of export section
module GLOBAL;
