# This file was automatically generated by bifcl from /build/sageaxcess-parsers/iosource/remote/src/const.bif (plugin mode).

export {
module PcapRemote;











} # end of export section
module GLOBAL;
