# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/analyzer/ntlm/types.bif (plugin mode).


export {
module NTLM;







} # end of export section
module GLOBAL;
