# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b7b677c4699aff95/src/logging/writers/sqlite/sqlite.bif (plugin mode).




export {
module LogSQLite;






} # end of export section
module GLOBAL;
