# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b7b677c4699aff95/src/input/readers/sqlite/sqlite.bif (plugin mode).


export {
module InputSQLite;





} # end of export section
module GLOBAL;
