# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b7b677c4699aff95/src/input/readers/binary/binary.bif (plugin mode).


export {
module InputBinary;



} # end of export section
module GLOBAL;
