# This file was automatically generated by bifcl from comm.bif (alternative mode).


##! Placeholder for Broker-based communication functionality, not enabled
##! by default.
export {
} # end of export section
module GLOBAL;
