# This file was automatically generated by bifcl from /build/sageaxcess-parsers/input/http/src/events.bif (plugin mode).

export {
global httpreader_message: event(message: string );


module InputHttp;




} # end of export section
module GLOBAL;
