# This file was automatically generated by bifcl from /build/sageaxcess-parsers/analyzer/ldap/src/events.bif (plugin mode).


export {
global ldap_message: event(c: connection , message: string );

global ldap_bind: event(c: connection , user: string );

global ldap_search: event(c: connection , base: string );

global ldap_response: event(c: connection , message: string , resultsCode: count );

} # end of export section
module GLOBAL;
