# This file was automatically generated by bifcl from /apps/buildAgent/work/800d28ace6035b11/src/input/readers/sqlite/sqlite.bif (plugin mode).


export {
module InputSQLite;





} # end of export section
module GLOBAL;
