# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b7b677c4699aff95/src/input/readers/raw/raw.bif (plugin mode).


export {
module InputRaw;



} # end of export section
module GLOBAL;
