# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/input/http/src/events.bif (plugin mode).

export {
global httpreader_message: event(message: string );


module InputHttp;




} # end of export section
module GLOBAL;
