# This file was automatically generated by bifcl from /apps/TeamCity/buildAgent/work/b1990390320eab7b/writer/zmq/src/zmq.bif (plugin mode).




export {


module LogZMQ;


















global LogZMQ::__detect_user: function(c: connection ) : string_vec ;


global LogZMQ::__get_system_stats: function() : system_stats ;

} # end of export section
module GLOBAL;
